const Icons = {
  linkedIn: "i-fa6-brands-linkedin",
  facebook: "i-fa6-brands-facebook",
  github: "i-fa6-brands-github",
  logo: "i-pajamas-organization",
  error: "material-symbols-error",
  warning: "material-symbols-warning",
  success: "material-symbols-check-circle",
  public: "material-symbols-light-public",
  private: "material-symbols-lock",
  like: "material-symbols-thumb-up",
  notLike: "material-symbols-thumb-up-outline",
  comment: "mdi-comment-outline",
  share: "mdi-share-outline",
  close: "material-symbols-close",
  send: "material-symbols-send",
  loading: "line-md-loading-twotone-loop",
  more: "mdi-dots-horizontal",
  edit: "material-symbols-edit-square-outline",
  delete: "material-symbols-delete-outline",
  notification: "material-symbols-notifications-outline",
  logout: "ic-round-log-out",
  personCheck: "material-symbols-person-check",
  personAdd: "material-symbols-person-add-rounded",
  personCancel: "material-symbols-person-cancel",
  personArrowRight: "tdesign-user-arrow-right-filled",
  personArrowLeft: "tdesign-user-arrow-left-filled",
  message: "mdi-facebook-messenger",
  arrowLeft: "material-symbols-arrow-left-alt",
  arrowRight: "material-symbols-arrow-right-alt",
};

export default Icons;
